spring:
  mvc:
    static-path-pattern: /view/**
  profiles:
    active: jpa
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create